            - name: liutongxu/liutongxu.github.io
  # You may pin to the exact commit or the version.
  # uses: joejordanbrown/fork-sync@91b292a645fff70f523e7819ecab60c7fd11b5e6
  uses: a546284907/a546284907.github.io
  with:
    # Owner of the forked repository
    owner: # optional
    # Token for the github API
    github_token: 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
    # Branch to track
    head: # optional, default is master
    # Branch to keep updated
    base: # optional, default is master
    # Merge method to use
    merge_method: # optional, default is merge
    # The title of the pull request
    pr_title: # optional, default is Fork Sync
    # The message in the pull request
    pr_message: # optional
    # ignore Exceptions
    ignore_fail: # optional
    # Automatically approve pull request before merge
    auto_approve: # optional
    # Usertoken for the user to auto approve the pull request
    personal_token: # optional
          
